using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Tests.Internal.Database.Models;

namespace Domain.Database.EntityTypeConfigurations;

internal sealed class DummyEntityTypeConfiguration : IEntityTypeConfiguration<DummyEntity>
{
    // Constructors
    public void Configure(EntityTypeBuilder<DummyEntity> builder)
    {
        ArgumentNullException.ThrowIfNull(builder);

        builder
            .Property(dummy => dummy.Name)
            .IsRequired()
            .HasMaxLength(100);

        builder
            .Property(dummy => dummy.AutoGeneratedId)
            .HasDefaultValueSql("newid()");
    }
}
